Migration script/openIMIS migration v1.2.0 - v1.3.0.sql

Related ticket:
https://openimis.atlassian.net/browse/OP-64

OP-64: Creation of user profiles

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

https://openimis.atlassian.net/browse/OP-328

Fix OP-328

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

TICKET: https://openimis.atlassian.net/browse/OTC-10

OTC-10: Procedures used for batch reports don't include claims with RunID != null

---

Migration script/openIMIS migration latest.sql

Changes:
- Added `User Profile` related rights to system role `IMIS Administrator`.
- Minor formatting changes
[https://openimis.atlassian.net/browse/OTC-8](https://openimis.atlassian.net/browse/OTC-8)

OTC-8: Authorisation doesn't work properly

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

The new policy status "Ready" was introduced. When we enquire about the insuree from web or mobile app, if the status is Ready it was displaying Expired. 
https://openimis.atlassian.net/browse/OTC-328

OTC-328: new policy status [Ready] accommodated in inquiry procedures

---

Empty databases/openIMIS_ONLINE.sql

Script has been modified to solve the error generated while creating a new database.
https://openimis.atlassian.net/browse/OP-357

OP : 357 - Error in creating new database with Online script

---

Migration script/openIMIS migration latest.sql

The latest migration script has been changed to resolve some bugs. A special character was removed and the sequence of the code is sorted. 
https://openimis.atlassian.net/browse/OP-358

OP-358 : Latest migration failed to run

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

uspSSRSClaimHistory procedure is changed in both online and migration scripts
https://openimis.atlassian.net/browse/OTC-65

OTC-65: RfC 101 Report Claim History

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

New table tblBulkControlNumbers 
Stored procedure uspReceiveControlNumber modified

OTC-364: Bulk control number request

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

2 new fields are added to the tblPayment
https://openimis.atlassian.net/browse/OTC-114

OTC-114 : CHF-5 Reconciliation of payment transactions

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Added a new field Quantity in tblItems

OE0-34: Split medical item ItemPackage into ItemForm and ItemAmount => openIMIS side

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

https://openimis.atlassian.net/browse/OTC-410
uspGetPolicyRenewal, dates are changed from string to Date datatype

OTC-410: Change all the dates from string to datetime in rest api

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

https://openimis.atlassian.net/browse/OTC-381

OTC-381: MV IMIS Policies::renewal  prompts are not displayed

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

https://openimis.atlassian.net/browse/OTC-415

OTC-415: MV: 500 error on GET /api/policy/ request

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Changes:
- Changed expected date input format in `uspUpdateClaimFromPhone` to `yyyy-MM-dd`
[https://openimis.atlassian.net/browse/OTC-431](https://openimis.atlassian.net/browse/OTC-431)

OTC-431: Update XML serializing format to yyyy-MM-dd

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Changes:
- Changed uspAPIGetCoverage to return dates as SQL `DATE` type instead of `VARCHAR`
[https://openimis.atlassian.net/browse/OP-373](https://openimis.atlassian.net/browse/OP-373)

OP-373: Enquiry function doesn't provide full data

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Changes:
- Fixed error in `ClaimRejectionStatus` declaration

OTC-438: Fixed ClaimRejectionStatus declaration

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Batch run fix applied by @delcroip on chf prod

Batch run chf prod fix

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Changes:
- Updated date conversion in `uspInsertFeedback`
[https://openimis.atlassian.net/browse/OP-459](https://openimis.atlassian.net/browse/OP-459)

OP-459: Feedback does not upload correctly

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

Changes:
- Added `RenewalUUID` to `uspGetPolicyRenewals`
[https://openimis.atlassian.net/browse/OP-187](https://openimis.atlassian.net/browse/OP-187)

OP-187: IMIS web and policies app: Renewal extracts dont work

---

Empty databases/openIMIS_ONLINE.sql
Migration script/openIMIS migration latest.sql

SelfRenewd Bit field added in the tblPolicy table

OTC-484: Fix renewal through USSD to use the bulk CN

---

sql/base/1_schema_tables.sql
sql/migrations/1_migration_latest.sql

https://openimis.atlassian.net/browse/OTC-507
https://openimis.atlassian.net/browse/OTC-73

OTC-73: Changing of the language of the user interface without logout/login

---

sql/base/1_schema_tables.sql
sql/migrations/1_migration_latest.sql

CreatedDate field added in tblPremium
https://openimis.atlassian.net/browse/OTC-511

OTC-511: Add a new column in tblPremium named CreatedDate

---

sql/base/1_schema_tables.sql
sql/migrations/1_migration_latest.sql

Created missing FK on paymentDetails and ControlNumber referencing to tblPayment

Missing FKs fixed

---

sql/base/1_schema_tables.sql
sql/migrations/1_migration_latest.sql

https://openimis.atlassian.net/browse/OTC-520

tblPayment > PhoneNumber length increased to 50 characters

---

sql/stored_procedures/uspSSRSOverviewOfCommissions.sql

https://openimis.atlassian.net/browse/OTC-70

OTC-70: RFC  103  Report Overview of Commissions

---

sql/migrations/1_migration_latest.sql
sql/stored_procedures/uspRelativeIndexCalculationMonthly.sql
sql/stored_procedures/uspSSRSGetClaimOverview.sql
sql/stored_procedures/uspSSRSPremiumDistribution.sql

https://openimis.atlassian.net/browse/OP-504

OP-504: system can not generate Contribution distribution report

---

sql/migrations/1_migration_latest.sql

SenderDisplayName added in tblEmailSettings
https://openimis.atlassian.net/browse/OP-248

OP-248: Remove hardcodded _CompanyName in EmailHandler

---

sql/stored_procedures/uspSSRSGetClaimOverview.sql

https://openimis.atlassian.net/browse/OTC-492
Changes:
- Procedure now checks claim data on regional level

OTC-492: Fixed claim overview procedure on a regional level.

---

sql/base/3_functions.sql
sql/migrations/1_migration_latest.sql

Ticket: [OP-238](https://openimis.atlassian.net/browse/OP-238)

OP-238: Fixed snapshot indicators report function

---

sql/base/1_schema_tables.sql
sql/migrations/1_migration_latest.sql

Missing xBulkControlNumebrs user data type created

OTC-619: Bulk CN Request, if the GePG server throws an error. IMIS fails to delete those requested CN from DB

---

sql/stored_procedures/uspRelativeIndexCalculationMonthly.sql
sql/stored_procedures/uspSSRSPremiumDistribution.sql

Rectified the formula in Premium Distribution and Relative Index Calculation Monthly

OTC-652: Contribution Distribution & Batch Index perform wrong calculation

---

sql/migrations/1_migration_latest.sql

https://openimis.atlassian.net/browse/OTC-687

Disabled some overlapping indexes

---

sql/stored_procedures/uspConsumeEnrollments.sql

Delete moved code
https://openimis.atlassian.net/browse/OSD-222

fix uspConsumeEnrollments

---

sql/stored_procedures/uspAPIGetClaims.sql

[https://openimis.atlassian.net/browse/OP-975](https://openimis.atlassian.net/browse/OP-975)
Changes:
- Added `InsureeNumber` and `LastUpdateDate` filters for `uspAPIGetClaims` stored procedure

OP-975 Enchance uspAPIGetClaims stored procedure to allow claim synchronisation

---

.github/workflows/openmis-module-test.yml
sql/stored_procedures/uspServiceItemEnquiry.sql

https://openimis.atlassian.net/browse/OTC-780
Update business logic: items/serives left is now being calculate as a sum of quantity in all valid claims assigned to insuree.
Related: https://github.com/openimis/openimis-be-policy_py/pull/39

OTC-780: update business logic

---

sql/stored_procedures/uspProcessbatch.sql

the old code does a process date between start and stop date BUT processdate is a DateTime so any datetime after 0.00 on the last day was NOT taken into account

fix end date for batch process

---

Dockerfile
script/run-initialization.sh

Puting ENV variable INIT_MODE as a 'string' prevented it from being updated from docker-compose args context.

Change type of env INIT_MODE from 'empty' to empty

---

sql/migrations/1_migration_latest.sql

https://openimis.atlassian.net/browse/OTC-1101
Added IF EXISTS check for Indexes

OTC-1101: MSSQL Migration script errors
